config/routes.rb
Rails.application.routes.draw do
  constraints :protocol => secure_protocol do
    devise_for(
      :users,
      :path         => "admin",
      :path_names   => {:sign_in => 'login', :sign_out => 'logout'},
      :controllers  => {:sessions => "islay/admin/sessions", :passwords => "islay/admin/passwords", :invitations => "islay/admin/users/invitations"}
    )
  end

  islay_admin 'islay' do
    root to: 'dashboard#index'

    # DASHBOARD & SEARCH
    get '/'         => 'dashboard#index',     :as => 'dashboard'
    get '/add-item' => 'dashboard#add_item',  :as => 'add_item'
    get '/search'   => 'search#index',        :as => 'search'

    # REPORTS
    get 'reports' => 'reports#index', :as => 'reports'

    # USERS
    resources :users do
      get '(/filter-:filter)(/sort-:sort)', :action => :index, :as => 'filter_and_sort', :on => :collection
      get :delete, :on => :member
    end

    # SITE CONFIG
    resources :site_configs, :path => 'settings'

    # PAGE CONTENT
    resources :pages, :only => %w(index edit update) do
      resources :features, :only => %w(new create edit update)
    end

    # ASSET LIBRARY
    scope :path => 'library' do
      get '/'                     => 'asset_library#index',   :as => 'asset_library'
      get '/browser(/:only).json' => 'asset_library#browser', :as => 'browser'

      resources(:asset_groups, :path => 'collections') do
        get :delete, :on => :member
        resources :asset_bulk_uploads, :path => 'bulk_uploads', :only => %w(new create)
      end

      resources :asset_tags, :path => 'tags', :only => %w(index show)

      # Processing
      resources :asset_processes, :path => 'processing', :controller => 'assets', :only => :index do
        collection do
          get '',                               :action => :processing, :as => 'index'
          get '(/filter-:filter)(/sort-:sort)', :action => :processing, :as => 'filter_and_sort'
          patch '',                             :action => :bulk_reprocess
        end
      end

      # Assets
      asset_resource = lambda do
        collection do
          get '(/filter-:filter)(/sort-:sort)', :action => :index, :as => 'filter_and_sort'
          get :bulk
          post :bulk, :action => 'bulk_create'
        end

        member do
          get :delete
          patch :reprocess
        end
      end

      asset_resources = %w(image document video audio)
      asset_resources.each do |s|
        as = "#{s}_assets".to_sym
        resources as, :path => "assets/#{s.pluralize}", :controller => 'assets', :defaults => {:type => s}, &asset_resource
      end

      resources :assets, :defaults => {:type => :assets}, &asset_resource
    end
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :page_assets do
    # Extracts an asset from the association by it's name.
    #
    # @param String name
    #
    # @return [Asset, nil]
    def by_name(name)
      if self[0]
        select {|a| a.name == name.to_s}.first
      else
        where(:name => name).first
      end
    end
  end

  has_many :features,           -> {order 'position ASC'}
  has_many :published_features, -> {order('position ASC').where('published = true')}, :class_name => "Feature"

  has_many :assets,     :through => :page_assets
  has_many :images,     :through => :page_assets, :source => :asset, :class_name => 'ImageAsset'
  has_many :documents,  :through => :page_assets, :source => :asset, :class_name => 'DocumentAsset'
  has_many :audio,      :through => :page_assets, :source => :asset, :class_name => 'AudioAsset'
  has_many :video,      :through => :page_assets, :source => :asset, :class_name => 'VideoAsset'

  track_user_edits
  validations_from_schema

  accepts_nested_attributes_for :features,
    :reject_if     => proc {|f| f.values.map(&:blank?).all?},
    :allow_destroy => true

  after_save :update_page_assets

  # Returns a stubbed out feature which serves as a 'template' for generating
  # new features.
  #
  # @return Feature
  def new_feature
    Feature.new(:published => true)
  end

  # This is a no-op. It just allows us to use the #new_feature in forms.
  #
  # @return nil
  def new_feature=(vals)
    nil
  end

  # A simple alias which helps us write out links to pages and features without
  # having to explicitly write out ids.
  #
  # @return String
  def to_param
    self[:slug]
  end

  # Returns the name defined in the configuration for this page.
  #
  # @return String
  def name
    definition.name
  end

  def each
    contents.each do |slug, val|
      yield(slug, content_type(slug), content_name(slug), val)
    end
  end

  # Checks to see if this page has been configured to have features attached to
  # it.
  #
  # @return Boolean
  def features?
    definition.features?
  end

  # The configuration and value merged together.
  #
  # @param [Symbol, String] name
  #
  # @return Hash
  def content_with_config(name)
    definition.contents[name.to_sym].merge(:value => contents[name])
  end

  # The contents defined against the page. For any contents that are missing,
  # we stub it out.
  #
  # @return Hash
  def contents
    @contents ||= definition.contents.inject({}) do |acc, c|
      name, config = c

      acc[name] = case config[:type]
      when :image
        page_assets.by_name(name)
      else
        entries[name.to_s] || ''
      end

      acc
    end
  end

  #Retrieve a single piece of content with its value
  def content(name)
    c = definition.contents[name]

    case c[:type]
    when :image
      page_assets.by_name(name)
    else
      entries[name.to_s] || ''
    end
  end

  class ContentsGroup
    def initialize(name, contents, page)
      @name = name
      @contents = contents
      @page = page
    end

    attr_reader :name, :contents

    def each
      @contents.each do |slug, val|
        yield(slug, @page.content_type(slug), @page.content_name(slug), @page.content(slug))
      end
    end
  end

  # Group the definitions by their 'group' value
  def grouped_contents
    definition.contents
      .reduce({}){|a, (k,v)| a[k] = content_with_config(k); a}
      .group_by{|k, v|v[:group]}.map do |(k, v)|
        values = v.to_h

        ContentsGroup.new(k, values, self)
      end
  end

  # Updates the content entries for the page.
  #
  # @param Hash updates
  #
  # @return Hash
  def contents=(updates)
    @contents = updates.inject({}) do |acc, u|
      name, val = u

      case content_type(name)
      when :image
        if val.blank?
          asset = page_assets.by_name(name)
          page_assets.destroy(asset) if asset

          acc[name] = nil
        else
          asset = page_assets.by_name(name) || page_assets.build(:name => name)
          asset.asset_id = val

          acc[name] = asset
        end
      else
        acc[name] = val
        self[:entries] = entries.merge(name => val)
      end

      acc
    end
    @contents

  end

  def content_name(name)
    definition.contents[name.to_sym][:name]
  end

  def content_type(name)
    definition.contents[name.to_sym][:type]
  end

  # Returns the content entries for the page, or stubs out an empty hash.
  #
  # @return Hash
  def entries
    self[:entries] ||= {}
  end

  private

  def definition
    @definition ||= Islay::Pages.definitions[slug.to_sym]
  end

  # Iterates over the page assets and saves them if they've been changed.
  #
  # @return Array<Asset>
  def update_page_assets
    page_assets.each {|pa| pa.save if pa.changed?}
  end
end

app/views/islay/admin/shared/_asset_picker.html.haml
%div.field.multi-images
  %label Images and documents
  %ul(data-name="#{f.object_name}[asset_ids][]")
    - f.object.assets.each do |asset|
      %li{:id => "asset-#{asset.id}"}
        .liner
          %label
            = asset.name
            = check_box_tag("#{f.object_name}[asset_ids][]", asset.id, :boolean => true)
          .frame
            = image_tag(asset.previews.url(:thumb))

app/views/islay/admin/shared/_breadcrumbs.html.haml
%ol.breadcrumb
  - breadcrumbs.each do |e|
    %li
      - if e[:opts].empty?
        %span= e[:title]
      - else
        = link_to(e[:title], path(*e[:opts]))

app/views/islay/admin/shared/_feedback_message.html.haml
.islay-info-message
  %i.icon.icon-info-sign
  %h3= message.html_safe

app/views/islay/admin/shared/_filter_nav.html.haml
%ul{:class => "filters fold-true"}
  %li.filter-label Show
  - filters.each do |name, url, current|
    %li
      - if current
        = link_to(name, url, :class => 'current')
      - else
        = link_to(name, url)

app/views/islay/admin/shared/_form_errors.html.haml
.islay-form-errors
  %i.icon.icon-warning-sign
  %h3 Oops - this couldn't be saved.
  %p Fields with problems are <span>highlighted.</span>

app/views/islay/admin/shared/_intro_text.html.haml
.islay-intro-text= render_markdown text

app/views/islay/admin/shared/_record_name.html.haml
%h2.islay-record-name
  %i{:class => "fa fa-#{icon}"}
  %span= name

= render_statuses

app/views/islay/admin/shared/_sort_nav.html.haml
%ul{:class => "sort fold-true"}
  %li.sort-label Sort by
  - entries.each do |name, url, current|
    %li
      - if current
        = link_to(name, url, :class => 'current')
      - else
        = link_to(name, url)

app/views/islay/admin/shared/_statuses.html.haml
%ul.statuses
  - statuses.each do |s|
    %li
      %span.key= s[:title]
      %span{:class => "value indicator #{s[:mode]}"}= s[:value]

app/views/islay/admin/shared/_sub_nav.html.haml
%ul.islay-sub-nav
  - entries.each do |e|
    %li
      - if e[:current]
        %a{:class => 'entry current', :href => e[:url]}
          %strong= e[:title]
      - else
        %a{:class => 'entry', :href => e[:url]}
          %strong= e[:title]

app/views/islay/admin/shared/delete.html.haml
- breadcrumb('Delete Confimation')

= resource_form(@resource, :method => :delete) do |f|
  = content do
    %h3 Really delete this record?
    %p This action can't be undone.
    - unless request.xhr?
      = cancel_button(nil, @cancel_url)
      = button_tag('Delete', :class => 'delete')